Zq!spring:
  application:
    name: usts-campus-services

  redis:
    redisson:
      file: classpath:redisson.yml

  mail:
    host: smtp.qq.com
    port: 465
    username: 3475315488@qq.com
    password: cizazhqmxtnncjag
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.103.202.40:13306/usts_campus_services?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: zq
    password: 241964Zq!
    hikari: # 可选的连接池配置（HikariCP）
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP


server:
  port: 9880
  servlet:
    context-path: /usts-campus-services
